Controllers/AbonneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using library.Models;

namespace library.Controllers
{
    public class AbonneController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly int Id;

        public AbonneController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Abonne
        public async Task<IActionResult> Index()
        {
              return _context.Abonnes != null ? 
                          View(await _context.Abonnes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Abonnes'  is null.");
        }

        // GET: Abonne/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Abonnes == null)
            {
                return NotFound();
            }

            var abonne = await _context.Abonnes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (abonne == null)
            {
                return NotFound();
            }

            return View(abonne);
        }

        // GET: Abonne/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Abonne/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Prenom")] Abonne abonne)
        {
            if (ModelState.IsValid)
            {
                _context.Add(abonne);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(abonne);
        }

        // GET: Abonne/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var abonne = await _context.Abonnes.FindAsync(id);
            if (abonne == null)
            {
                return NotFound();
            }

            return View(abonne);
        }

        // POST: Abonne/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Prenom")] Abonne abonne)
        {
            if (id != abonne.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Update the entry in the database
                    _context.Update(abonne);

                    // Save changes to the database
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AbonneExists(abonne.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Redirect to the Index action after a successful update
                return RedirectToAction(nameof(Index));
            }

            // If the model state is not valid, return to the edit view with the provided model
            return View(abonne);
        }

        // GET: Abonne/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Abonnes == null)
            {
                return NotFound();
            }

            var abonne = await _context.Abonnes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (abonne == null)
            {
                return NotFound();
            }

            return View(abonne);
        }

        // POST: Abonne/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Abonnes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Abonnes'  is null.");
            }
            var abonne = await _context.Abonnes.FindAsync(id);
            if (abonne != null)
            {
                _context.Abonnes.Remove(abonne);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AbonneExists(int id)
        {
          return (_context.Abonnes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Admin/BookEm.cshtml
@model List<library.Models.Emprunt>
@{
    Layout = "_AdminPanel"; // Spécifie un layout différent pour le backoffice
}

<style>
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    img {
        max-width: 100px; /* Ajustez la taille maximale de l'image selon vos besoins */
        height: auto;
    }
</style>

<h2>Livres Empruntés par @ViewData["SubscriberName"]</h2>

@if (Model.Any())
{
    <table>
        <thead>
            <tr>
                <th>EmpruntID</th>
                <th>LivreId</th>
                <th>DateEmprunt</th>
                <th>DateRetour</th>
                <th>Titre de livre</th>
                <th>Image</th>

                <!-- Ajouter d'autres colonnes pertinentes au besoin -->
            </tr>
        </thead>
        <tbody>
            @foreach (var emprunt in Model)
            {
                <tr>
                    <td>@emprunt.Id</td>
                    <td>@emprunt.LivreId</td>
                    <td>@emprunt.DateEmprunt</td>
                    <td>@emprunt.DateRetour</td>
                    <td>@emprunt.Livre.Titre</td>
                    <td>  <img src="/images/@emprunt.Livre.ImageUrl" class="card-img-top" alt="Image du livre"> </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Aucun livre emprunté par cet abonné.</p>
}
<a asp-controller="Abonne" asp-action="Index" class="btn btn-primary m-4">Retour à la liste des abonnés</a>

Views/Admin/Index.cshtml
@{
    Layout = "_AdminPanel"; // Spécifie un layout différent pour le backoffice
}
<div class="card">
    <div class="card-header">
        Admin Panel - Home Page
    </div>
    <div class="card-body">
        Welcome to the Admin Panel, use the sidebar to navigate between the different options.
    </div>
</div>

Views/Admin/MesaageList.cshtml
@{
    Layout = "_AdminPanel"; // Spécifie un layout différent pour le backoffice
}

@model IEnumerable<library.Models.Message>

@{
    ViewData["Title"] = "MesaageList";
}

<h1>MesaageList</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contenu)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contenu)
            </td>
            <td>
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>